### ISSUE TITLE
[Errata]- "AWS Certified Cloud Practioner Study Guide" by Ben Piper and Ben Clinton

### ISSUE THREAD

**Issue by CJGgithub999** [awsccp/awsccp.github.io#19]
In the title "AWS Certified Cloud Practioner Study Guide" by Ben Piper and Ben Clinton...

In Chapter 4, Review Question #4 on page 63 asks "Which of the following are not globally based AWS services (select TWO)"

Of the choices, A (RDS) and C (EC2) are clearly not globally based.

Yet the answer provided is B (Route 53) and D (CloudFront)-- both of which ARE global,

The correct answer should be A and C.

On a different note, when I go to the Simple Monthly Calculator, my AWS M Console indicates that tool is being retired.

Many thanks!  If I am wrong, my apologies.    

Chris Garigliano
SF FRB
chris.garigliano@sf.frb.org

**Please include any other comments or questions**

**Comment by KaranAhuja94** [comment]
Refer https://github.com/awsccp/awsccp.github.io/issues/2
The correct answer is A and C.

**Comment by dbclinton** [comment]
Indeed, we're aware of that mistake in the chapter 4 answer and it will be corrected.
Regarding the deprecation of the old (and much loved) Simple Monthly Calculator, we're aware of that, too. It's come up here:

> I just noticed that myself a couple of weeks ago. There aren't any updates planned for the exam in the near future that I'm aware of, so I think you'll be fine with the existing tool (and I don't remember any detailed exam questions on the workings of the tool in any case).
> But there are problems with this change that have nothing to do with the exam. For one thing the new Pricing Calculator isn't even fully functional yet: many AWS services aren't even set up there. And another problem is that the old calculator had integrations with specific AWS services (like CloudFormation) that will break.
> And, from a personal perspective, I much prefer the old tool.
