### ISSUE TITLE
[Errata]The answer for: Chapter 4: Understanding the AWS Environment

### ISSUE THREAD

**Issue by cacheampong** [awsccp/awsccp.github.io#2]
**Please describe the error you're reporting**
The answer for Chapter 4 shows B, D. Even though the explanation seems right.
Please verify.
**Please indicate the chapter or appendix, section, and page number where the error appears (if applicable)**
Appendix A
Answers to Review Questions
**Please include any other comments or questions**

**Comment by dbclinton** [comment]
Hi,
Would you mind providing the specific question. I'm not sure which one you're referring to.
Thanks!

**Comment by cacheampong** [comment]
4. Which of the following are not globally based AWS services?
(Select TWO.)
A. RDS
B. Route 53
C. EC2
D. CloudFront


4. B, D. Relational Database Service (RDS) and EC2 both use
resources that can exist in only one Region. Route 53 and
CloudFront are truly global services in that they’re not located in
or restricted to any single AWS Region.

**Comment by dbclinton** [comment]
Thanks. This answer is - to the best of my knowledge - correct. If you look at the region indicator at the top right of the management console when in the Route 53 or CloudFront pages, you'll see "Global". On the RDS or EC2 pages, on the other hand, you'll see a specific region.
The tricky service is S3. Even though you'll see "Global" on its page, you still need to specify a region for each bucket. I guess they just  couldn't quite make up their minds. :)

**Comment by cacheampong** [comment]
But the question says which of the following are "NOT".
The explanation is correct but I think your question is not correct.

**Comment by dbclinton** [comment]
Whoops. You're absolutely correct! Perhaps this is why they discourage us from using "not" in this kind of question. :) 
I'll have to get that one fixed.
Thanks!

**Comment by cacheampong** [comment]
Please have that fixed in the quiz as well because it is the same there too.
Thanks a lot for your prompt response.

**Comment by wsunarko** [comment]
Hard to learn when the guidance is wrong, I have doubts to many other answers from the book.
Please review and correct it before publishing it.
