### ISSUE TITLE
Question 4: Chapter 4

### ISSUE THREAD

**Issue by oafuape** [awsccp/awsccp.github.io#31]
**Please describe the error you're reporting**
4. Which of the following are not globally based AWS services? (Select TWO.)
A. RDS
B. Route 53
C. EC2
D. CloudFront
**Please indicate the chapter or appendix, section, and page number where the error appears (if applicable)**
Page 235: 
4. B, D. Relational Database Service (RDS) and EC2 both use resources that can exist in only
one Region. Route 53 and CloudFront are truly global services in that they’re not located in
or restricted to any single AWS Region.
**Please include any other comments or questions**
Either change question to mean which are or change the answers to A and C

**Comment by dbclinton** [comment]
Thanks. We're actually already aware of this error and it's fixed in the new edition - coming soon to a bookstore near you, assuming you still have any bookstores near you. :)
Take care!
David
