### ISSUE TITLE
[Errata] Online test bank answer options listed as numbers instead of letters

### ISSUE THREAD

**Issue by neatpit** [awsccp/awsccp.github.io#33]
Hi, 

Unsure if this considered errata or not. Each chapter review question has a question number and then each multiple choice option is also a number. See attached. This format isn't the end of the world, but it makes the mapping to the Appendix A Answers a bit more tedious. 
![Capture](https://user-images.githubusercontent.com/70908841/92427781-3d7d9f80-f142-11ea-8fad-3b4054fa902f.JPG)

**Comment by dbclinton** [comment]
I believe that's an unavoidable product of the online system for some technical reason. The book itself assigns letters to the answers both in the chapter and in the appendix.
