### ISSUE TITLE
[Errata] Chapter 5, Question 14 Incorrect Answer

### ISSUE THREAD

**Issue by Serpico1979** [awsccp/awsccp.github.io#43]
**AWS Certified Cloud Practitioner" book (printed 02/08/2021)**

The Question 14 on chapter 5 ask:
**What will IAM users with AWS Management Console access need to successfully log in?**

**A**. Their username, accont_number, and a password
**B**. Their Username e Password
**C**. Their accont_number, and secret access key
**D**. Their Username, Password and secret access key

I have chosen answer **A** while the correct one seems to be **B**
From the console (as image attached) by logging in as IAM users there are three fields and not just the username and password.
What is the correct answer? Thanks"!

![AWS_Consolle_Login](https://user-images.githubusercontent.com/101264469/157448690-cf15f521-4f50-4ee1-a1d8-62f7a6375e0c.png)

**Comment by dbclinton** [comment]
There's no question that you were correct. Logging in as an AWS user requires an account number (or user alias), the user name, and the password. I'll have to take a look to see if that questions needs an update.
Thanks!
