### ISSUE TITLE
[Errata] Review questions / answers

### ISSUE THREAD

**Issue by kaoscoach** [awsccp/awsccp.github.io#5]
**Please describe the error you're reporting**
Not an error per se. Just finished Chapter 1 and was reviewing my answers. I noticed that the answers to the questions are numbered 1, 2, 3, etc. but the answers in the Appendix are lettered A, B, C, etc. Just seems a bit sloppy.

**Please indicate the chapter or appendix, section, and page number where the error appears (if applicable)**
All Chapters and Appendix A

**Please include any other comments or questions**

**Comment by dbclinton** [comment]
Hi,
You're not the first reader to mention this. I'm going to look into it to see if it can be fixed.
Thanks!

**Comment by dbclinton** [comment]
Hello again. 
I actually got my first look at the print book and I see both the assessment questions and answers are identified using letters. However, I'm told that the Kindle version (which I haven't seen) does use numbers for the answers. This is an unfortunate (and annoying) inconvenience, but there's apparently no way to fix it: it all hangs on the way the Kindle software generates their e-books and that's not changing anytime soon. 
Thanks again for pointing this out,
David

**Comment by kaoscoach** [comment]
I am using the Kindle version. Thanks for the message.

________________________________

**Comment by benpiper** [comment]
Tracked in [https://github.com/awsccp/awsccp.github.io/issues/3](https://github.com/awsccp/awsccp.github.io/issues/3)
