### ISSUE TITLE
[Errata] Chapter 4, Review Question 4

### ISSUE THREAD

**Issue by dzitzels1** [awsccp/awsccp.github.io#7]
**Please describe the error you're reporting**
The answers to this Review Question are wrong.

**Please indicate the chapter or appendix, section, and page number where the error appears (if applicable)**
Chapter 4, Review Question 4, page 63

**Please include any other comments or questions**
The question is:
"Which of the following are _not_ globally based AWS services? (Select TWO.)"
A. RDS
B. Route 53
C. EC2
D. CloudFront

The explanation on page 235 is as follows:
B, D.  Relational Database Service (RDS) and EC2 both use resources that can exist in only one Region.  Route 53 and CloudFront are truly global services in that they're not located in or restricted to any single AWS region.

According to the explanation, clearly the answer should be A, C.

**Comment by dbclinton** [comment]
Hi,
That one is indeed wrong. The correct answers are A and C. We've already submitted it for correction.
Thanks!

**Comment by benpiper** [comment]
Tracked in [https://github.com/awsccp/awsccp.github.io/issues/6](https://github.com/awsccp/awsccp.github.io/issues/6)
